cc_binary (
  name = "500",
  srcs = [
    "500.cc",
  ],
  deps = [
    "//numbers:prime_lib",
    "//numbers:modular_lib",
  ],
)
cc_binary (
  name = "185",
  srcs = [
    "185.cc",
  ],
)
cc_binary (
  name = "549",
  srcs = [
    "549.cc",
  ],
  deps = [
    "//numbers:prime_lib",
  ],
)
cc_binary (
  name = "491",
  srcs = [
    "491.cc",
  ],
)
